spring:
  application:
    name: member
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#
#    url: jdbc:postgresql://member_db:5432/${MEMBER_DB_NAME}
#    username: ${MEMBER_DB_USER}
#    password: ${MEMBER_DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
